project:
  type: book
  output-dir: docs

book:
  title: "All About Me"
  author: "Illona Nasywa Hannum"
  chapters:
    - index.qmd
    - All_About_me/index.qmd
    - My_Song_for_You/index.qmd
    - My_Stories_for_You/index.qmd
    - My_Shapes/index.qmd
    - My_Personal_Reviews/index.qmd
    - My_Concepts/index.qmd
    - My_Opinions/index.qmd
    - My_Innovations/index.qmd
    - My_Knowledge/index.qmd
    - My_Professional_Reviews/index.qmd
    - summary.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    toc: true
